### ISSUE TITLE
LaunchButtonConfigTool, ProgrammableButtonConfig and ConsumerControlConfig do not want to compile

### ISSUE THREAD

**Issue by nazar-pc** [kiibohd/kll#14]
I have 2 lines in kll v0.3d file:
```
U"F4"  : CONS"EmailReader";
U"F5"  : CONS"ConsumerControlConfig";
```

The first line compiles and works properly, however, seconds gives me an error during compilation:
```
-- Compiler Family:
arm
-- Compiler Selected:
gcc
-- Chip Selected:
mk20dx256
-- Chip Family:
mk20dx
-- CPU Selected:
cortex-m4
-- Compiler Source Files:
Lib/mk20dx.c;Lib/delay.c
-- Bootloader Type:
Teensy
-- Detected Scan Module Source Files:
Scan/MatrixARM/matrix_scan.c;Scan/Rapoo_E9070/scan_loop.c
-- Detected Macro Module Source Files:
Macro/PartialMap/macro.c;Macro/PartialMap/result.c;Macro/PartialMap/trigger.c
-- Detected Output Module Source Files:
Output/pjrcUSB/output_com.c;Output/pjrcUSB/arm/usb_desc.c;Output/pjrcUSB/arm/usb_dev.c;Output/pjrcUSB/arm/usb_joystick.c;Output/pjrcUSB/arm/usb_keyboard.c;Output/pjrcUSB/arm/usb_mem.c;Output/pjrcUSB/arm/usb_mouse.c;Output/pjrcUSB/arm/usb_rawio.c;Output/pjrcUSB/arm/usb_serial.c
-- Detected Debug Module Source Files:
Debug/cli/cli.c;Debug/led/led.c;Debug/print/print.c
-- Detected Layout Files:
/sources/Scan/MatrixARM/capabilities.kll
/sources/Macro/PartialMap/capabilities.kll
/sources/Output/pjrcUSB/capabilities.kll
/sources/Scan/Rapoo_E9070/scancode_map.kll
/sources/kll/layouts/stdFuncMap.kll
/sources/kll/layouts/Rapoo_E9070_Fn.kll
-- Configuring done
-- Generating done
-- Build files have been written to: /sources/Keyboards/Rapoo_E9070.gcc
[  4%] Generating KLL Layout
ERROR: 'CONSUMERCONTROLCONFIG' is an invalid USB HID Code Lookup...
Traceback (most recent call last):
  File "/sources/kll/funcparserlib/parser.py", line 204, in _or
    return self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 348, in _some
    raise NoParseError('got unexpected token', s, t)
funcparserlib.parser.NoParseError: got unexpected token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/kll/funcparserlib/parser.py", line 204, in _or
    return self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 206, in _or
    return other.run(tokens, State(s.pos, e.state.max))
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 348, in _some
    raise NoParseError('got unexpected token', s, t)
funcparserlib.parser.NoParseError: got unexpected token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/kll/funcparserlib/parser.py", line 204, in _or
    return self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 348, in _some
    raise NoParseError('got unexpected token', s, t)
funcparserlib.parser.NoParseError: got unexpected token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/kll/funcparserlib/parser.py", line 204, in _or
    return self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 206, in _or
    return other.run(tokens, State(s.pos, e.state.max))
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 206, in _or
    return other.run(tokens, State(s.pos, e.state.max))
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 348, in _some
    raise NoParseError('got unexpected token', s, t)
funcparserlib.parser.NoParseError: got unexpected token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/kll/funcparserlib/parser.py", line 204, in _or
    return self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 348, in _some
    raise NoParseError('got unexpected token', s, t)
funcparserlib.parser.NoParseError: got unexpected token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/kll/funcparserlib/parser.py", line 204, in _or
    return self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 206, in _or
    return other.run(tokens, State(s.pos, e.state.max))
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 348, in _some
    raise NoParseError('got unexpected token', s, t)
funcparserlib.parser.NoParseError: got unexpected token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/kll/funcparserlib/parser.py", line 204, in _or
    return self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 206, in _or
    return other.run(tokens, State(s.pos, e.state.max))
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 348, in _some
    raise NoParseError('got unexpected token', s, t)
funcparserlib.parser.NoParseError: got unexpected token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/kll/funcparserlib/parser.py", line 204, in _or
    return self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 206, in _or
    return other.run(tokens, State(s.pos, e.state.max))
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 348, in _some
    raise NoParseError('got unexpected token', s, t)
funcparserlib.parser.NoParseError: got unexpected token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/kll/funcparserlib/parser.py", line 204, in _or
    return self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 206, in _or
    return other.run(tokens, State(s.pos, e.state.max))
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 348, in _some
    raise NoParseError('got unexpected token', s, t)
funcparserlib.parser.NoParseError: got unexpected token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../kll/kll.py", line 721, in processKLLFile
    tree = parse( tokenSequence )
  File "../../kll/kll.py", line 707, in parse
    return kll_file.parse( tokenSequence )
  File "/sources/kll/funcparserlib/parser.py", line 146, in parse
    (tree, _) = self.run(tokens, State())
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 204, in _or
    return self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 318, in _many
    (v, s) = p.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 204, in _or
    return self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 204, in _or
    return self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 204, in _or
    return self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 206, in _or
    return other.run(tokens, State(s.pos, e.state.max))
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 183, in _add
    (v2, s3) = other.run(tokens, s2)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 204, in _or
    return self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 204, in _or
    return self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 182, in _add
    (v1, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 204, in _or
    return self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 206, in _or
    return other.run(tokens, State(s.pos, e.state.max))
  File "/sources/kll/funcparserlib/parser.py", line 224, in _shift
    (v, s2) = self.run(tokens, s)
  File "/sources/kll/funcparserlib/parser.py", line 225, in _shift
    return f(v), s2
  File "../../kll/kll.py", line 248, in make_consCode
    return make_hidCode( 'ConsCode', token )
  File "../../kll/kll.py", line 215, in make_hidCode
    hidCode = kll_hid_lookup_dictionary[ type ][ token[1:-1].upper() ][1]
KeyError: 'CONSUMERCONTROLCONFIG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../kll/kll.py", line 797, in <module>
    processKLLFile( filename )
  File "../../kll/kll.py", line 724, in processKLLFile
    if err.token.value != '<=':
AttributeError: 'KeyError' object has no attribute 'token'
CMakeFiles/kiibohd.elf.dir/build.make:66: recipe for target 'generatedKeymap.h' failed
make[2]: *** [generatedKeymap.h] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/kiibohd.elf.dir/all' failed
make[1]: *** [CMakeFiles/kiibohd.elf.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Error in make. Exiting...
```

**Comment by nazar-pc** [comment]
Still an issue over a year later. @haata, can you take a look?
Here is what happens on latest master branch of `controller`:
```
root@d3c934a85117:/controller/Keyboards# ./Rapoo_E9070.bash 
linux-gnu/Linux is supported.
Unix Build
Selected Generator: Ninja
linux-gnu.Rapoo_E9070.gcc.ninja
-- Build CPU Detected:
x86_64
-- Build Kernel Detected:
Linux 4.15.0-24-generic
-- Compiler Family:
arm
-- Compiler Selected:
gcc
-- Chip Selected:
mk20dx256
-- Chip Family:
mk2x
-- CPU Selected:
cortex-m4
-- Compiler Source Files:
Lib/kinetis.c;Lib/delay.c;Lib/entropy.c;Lib/periodic.c;Lib/time.c
-- Bootloader Type:
Teensy
-- Full Compiler:
/usr/bin/arm-none-eabi-gcc 
-- Detected Scan Module Source Files:
Scan/Devices/MatrixARMPeriodic/matrix_scan.c;Scan/Rapoo_E9070/scan_loop.c
-- Detected Macro Module Source Files:
Macro/PartialMap/kll.c;Macro/PartialMap/layer.c;Macro/PartialMap/macro.c;Macro/PartialMap/result.c;Macro/PartialMap/trigger.c
-- Detected Output Module Source Files:
Output/HID-IO/hidio_com.c;Output/Interface/output_gen.c;Output/USB/output_com.c;Output/USB/output_usb.c;Output/USB/arm/usb_desc.c;Output/USB/arm/usb_dev.c;Output/USB/arm/usb_joystick.c;Output/USB/arm/usb_keyboard.c;Output/USB/arm/usb_mem.c;Output/USB/arm/usb_mouse.c;Output/USB/arm/usb_rawio.c;Output/USB/arm/usb_serial.c
-- Detected Debug Module Source Files:
Debug/cli/cli.c;Debug/latency/latency.c;Debug/led/led.c;Debug/print/print.c
-- Build OS Detected:
Ubuntu 16.04.4 LTS xenial
-- Detected Layout Files:
/controller/Scan/Devices/MatrixARMPeriodic/capabilities.kll
/controller/Macro/PartialMap/capabilities.kll
/controller/Output/HID-IO/capabilities.kll
/controller/Output/USB/capabilities.kll
/controller/Debug/latency/capabilities.kll
/controller/Scan/Rapoo_E9070/scancode_map.kll
/controller/kll/layouts/stdFuncMap.kll
/controller/kll/layouts/Rapoo_E9070_Fn.kll
-- Configuring done
-- Generating done
-- Build files have been written to: /controller/Keyboards/linux-gnu.Rapoo_E9070.gcc.ninja
[1/33] Generating KLL Layout
FAILED: cd /controller/Keyboards/linux-gnu.Rapoo_E9070.gcc.ninja && python3 /controller/kll/kll --version && python3 /controller/kll/kll --kiibohd-debug --config /controller/Scan/Devices/MatrixARMPeriodic/capabilities.kll /controller/Macro/PartialMap/capabilities.kll /controller/Output/HID-IO/capabilities.kll /controller/Output/USB/capabilities.kll /controller/Debug/latency/capabilities.kll --base /controller/Scan/Rapoo_E9070/scancode_map.kll --default /controller/kll/layouts/stdFuncMap.kll --partial /controller/kll/layouts/Rapoo_E9070_Fn.kll --emitter kiibohd --def-template /controller/kll/templates/kiibohdDefs.h --map-template /controller/kll/templates/kiibohdKeymap.h --pixel-template /controller/kll/templates/kiibohdPixelmap.c --def-output kll_defs.h --map-output generatedKeymap.h --pixel-output generatedPixelmap.c
kll BETA 0.5c.bc801e1d16ff4b680ffdd46ba3c7a0939cd09f88 - 2018-04-30 22:57:16 -0700
ERROR: 'CONSUMERCONTROLCONFIG' is an invalid USB HID Code Lookup...
  File "/controller/kll/common/parse.py", line 101, in hidCode
    hidCode = kll_hid_lookup_dictionary[type][token[1:-1].upper()][1]
Invalid dictionary lookup, check syntax.
ERROR: OperationSpecificsStage:parse -> /tmp/kll/kll_layouts@['Rapoo_E9070_Fn']_processed.kll:13
ERROR: Invalid stage status 'Incomplete' for 'OperationSpecificsStage'.
ninja: build stopped: subcommand failed.
Error in build. Exiting...
```

Changes similar to previously closed PR still work.

**Comment by haata** [comment]
Hmm, rename `ConsumerControlConfig` to `Consumer Control Config`.

https://github.com/hid-io/layouts/blob/master/base/base.json#L1607

**Comment by haata** [comment]
Closing unless there are any more issues.
